apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: twmj009p4-python 
  janus-idp.io/tekton: twmj009p4-python
  backstage.io/kubernetes-id: twmj009p4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: twmj009p4-python
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml